# Generated by Django 5.0.1 on 2024-01-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(verbose_name="Birth date"),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_be_contacted",
            field=models.BooleanField(verbose_name="Can be contacted"),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_data_be_shared",
            field=models.BooleanField(verbose_name="Accept to share data"),
        ),
    ]
